name: 🌊 Daily Data Fetch

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  fetch_and_publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: ⚡️ TEST ECRITURE DIRECTE
        # Cette commande écrit directement un GeoJSON valide
        run: |
          mkdir -p data # Crée le dossier data si non existant
          echo '{"type": "FeatureCollection", "metadata": {"status": "SUCCES TEST BASH"}, "features": []}' > data/marine_data.geojson
        
      - name: Commit et Push (Si réussite)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '🤖 DECRET ROYAL: TEST BASH REUSSI. Fichier créé.'
          files: 'data/marine_data.geojson'
