name: 🌊 Daily Data Fetch

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  fetch_and_publish:
    runs-on: ubuntu-latest
    
    # AJOUT ESSENTIEL POUR LE COMMIT :
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: ⚡️ CRÉATION DU FICHIER (TEST BASH)
        run: |
          mkdir -p data 
          echo '{"type": "FeatureCollection", "metadata": {"status": "SUCCES GARANTI"}, "features": []}' > data/marine_data.geojson
        
      - name: Commit et Push des données
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '🤖 DECRET ROYAL: SUCCES FINAL. Permission corrigée.'
          file_pattern: 'data/marine_data.geojson'
